version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustive
    - exhaustruct
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - gosmopolitan
    - ireturn
    - lll
    - mnd
    - nlreturn
    - noctx
    - noinlineerr
    - nonamedreturns
    - tagalign
    - tagliatelle
    - testpackage
    - paralleltest
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: exported
          arguments: ["disable-checks-on-types", "disable-checks-on-constants"]
        - name: var-naming
          disabled: true
        - name: line-length-limit
          arguments: [128]
        - name: add-constant
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: unhandled-error
          arguments:
            - "^strings\\.Builder\\.Write(?:Byte|Rune|String)?$"
        - name: nested-structs
          disabled: true
        - name: bare-return
          disabled: true
        - name: unchecked-type-assertion
          arguments:
            - accept-ignored-assertion-result: true
        - name: enforce-switch-style
          disabled: true
        - name: package-comments
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: function-length
          arguments: [0, 100]
    gosec:
      excludes:
        - G401
        - G402
        - G403
        - G404
        - G405
        - G406
        - G501
        - G502
        - G503
        - G504
        - G505
        - G506
        - G507
  exclusions:
    paths:
      - tools/
run:
  tests: false
  timeout: 3m