version: 2
project_name: "bilibili"

before:
  hooks:
    - go mod tidy

builds:
  - no_main_check: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64