name: GoFmt

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: gofmt
        if: github.repository_owner == 'CuteReimu'
        continue-on-error: true
        run: |
          if [ "$(gofmt -s -l -w . | wc -l)" -gt 0 ]; then
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "gofmt"
          git push
          fi