name: GoFmt

on:
  pull_request_target:
    branches: [ master ]

jobs:

  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: gofmt
        run: |
          if [ "$(gofmt -s -l -w . | wc -l)" -gt 0 ]; then
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "gofmt"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GH_PAT }}
